language: node_js
node_js:
  - "0.12"

addons:
  sauce_connect: true

env:
  global:
    # Firebase
    - secure: "DE+AW9aoRyHM3q2xyP/aTCKyEhNGvh+6gf6catDoOHtkv/pRBCSL4tLOCfkidCezf0r8nRxY+pJtlFcK1ClRE5dvs3SywaOZ9XBtisWFTQuiMkCMXuMTiJ+SarJoJCbGM44Q88qGYz0XJfF4av+XyJQcAgC/PF9r+VpSarkGixNl12i2nMw1/BKS26jov0vaxqgZj+xi7GQuL8iaHh086LijU/36sEJ/IvEwSqdp/qoYhDbx036MBwWKceakqA3DroQ/WDck93NsztpJD8g8GO9XF6pRKT4G+WcBjdUoFo3G6cZN49QVxLIFdgQhM6tPlC2up0wgegKNAiX4W9IkDkxGvAanIXgFRCoqNT/FVkPO4UtBZmaOHqqWME/lc0+WO7ghYbM2YETxH3S9I4sgrTlDsANIx/fO8c5eK8bQuMMPtlyAFtC6Fev63LJHlW0mTMJsqHtYxnsknho6YwPHqSgnDSQaHL8irD+d8WMXrxXPIemGbb6iuaVRtZQCgnk2NbnfTGEUf0WMQvtSYn/7J1C6FfKKBtBJwPNw2reM+TRe/B7YJ7Wpy7U9HieRKaSwePZPGr6uIijb9N6aRm9zMXR9s23Rtpa2itTJ9H89Yj9Y7hB2NqU+diem4wAPeQNuLl70qUDUr595JrvlCXNBtTyPI8vJ/2XKKrfaVhRp98s="
    # Tsd
    - secure: "oOmAhYR4Jv2zhcn3Wn6fYbZBdWFMMwr5o6+7iYOPoVoL+aHQFKrM7ahDpEquCKXwTUgsq69IjauPcJWTsJ+uq0KeA3oJEewKB79VGynRZtV1YEWa4aezCFYP6dXmcYzN+zTrHq6HvSl3nMmmvT2ssklo2EW5AN6BZ7THDSNEgEKpWAehH2uZ3AZjukbJt8BsRxM+42ZtQxIGgkcRWJJ7XBAoNRAe8/Epy1oGe5UXFs3JnjwsXb6w4yDJ+J/MllgpxGphTIAUwYzT+MGSeLjGwwuxdZ+v6QTNpOF+IoOnBmYlm9RvkdeYmGseOPA/EjHs55ZmPBMV8c17eUcnINaU8m+g/rsJqFcKBUgydmsh3QdxZJBEx2QY6atRLe6FOxEzypjvXHGkXbotp+T6mB5ZBtuvui+kNzEYNCPMHkVVLg0i/iOEEZ0dbHI3qrlBxS6FUKn9PY926YrUcbD3YZfsfdEbDLgt/d9+7+uaqMG7IyADeolUC4Sa6Mr1FRUme5OIAjtf6ibn6Vqv1/gZ27EjK5LkbfKPCke6mNnlgwAfdMQAgrm17u3jJMXGi1Dv1uwgeiVjqUYWF2VPCPE4V/QE+Hwrlts1LdRVQSiMT2q4YvG7yv3a7BqHAg+IUy097eZT9DPV8Vu7BcFWdUszqw1otBgMRtksxuDeaAyOWqs/HTU="
    # Saucelabs
    - SAUCE_USERNAME=rolandjitsu
    - secure: "JCabDo1wjn+rcfl9R3lXnF0XqPn5xOcm4zUo0+dSAgMiv+/3mC38KGo/fvbsdQzyxTU3hrYUOYk3cp/iI6MQE/h+u/sD0Ixo1B77inGZarSiQqyh93lDPF02NBziwWKOw/KA9PGehlE6SZ4qa55V4A3iOV4+fbwHGzmr/I9QNomAKybAiHrBx/1yA5Q8mFD9AtSgeP9f9vGFqFFFPJIikHdNQL4kF/PoDrn763jHLFVdk1BFd8U/ZV61fArtfxvb1ySMZuIp6GVvOjbDp/hG4hCdcuWiSF0TGQWcvxrzty26mP5qh75yKu9G28l7ln1PLqN/xLEDX7Bv2O5v57eeAGVh49AJjAab3brm69L6KOdJdOnYpCTb6ssrajJMCv+10UV97PYt8yYsUsn+Kg8f8jB0qOHeFwGX0EE9xNKXJOORjRt9gIg/H71XBGXQCMnqHWU2/3NY4XcT6aj4NNv8PkdxXkgV1x2HXs7MqUIk4pfhV+RJd9pbK0WaKc9sAOydyYW+ziEZXk6vCXnTlVoCuCzAFOx74OTuwk0fmNRD8knMW++evyImd5aSc6ENGhvu7MTUehfNSTH+fCSZhT1Ao1E2pSrOAWYl0wHBPPNRsQNEHf7MrzcWB42uM3icPsmoKZHs7+UB+lmY0ejxkI/jj8U2+BBVtf+QthETCDLj1k4="

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install: npm install --loglevel silent

before_script: ./scripts/ci/clean.sh

script:
  - ./scripts/ci/build.sh
  - ./scripts/ci/test.sh
  - ./scripts/ci/deploy.sh

after_script: ./scripts/ci/clean.sh

notifications:
  email:
    on_success: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e8e1d417898b5281d968
    on_success: change
    on_failure: always
    on_start: never